### ISSUE TITLE
Add env.sh for NCAR Cheyenne

### ISSUE THREAD

**Issue by jsimkins2** [NOAA-GFDL/FRE-NCtools#139]
NCAR Cheyenne is a popular supercomputer for research scientists. It would be helpful to have an `env.sh` for this system. I've tried many iterations of the installation process, but have not been able to successfully install FRE-NCtools for Cheyenne. Here is the general process I've tried.

```
git clone --recursive https://github.com/NOAA-GFDL/FRE-NCtools
cd FRE-NCtools
git submodule update --init --recursive

autoreconf -i
export PATH=/glade/work/jsimkins/FRE-NCtools:$PATH

mkdir bin/

./configure --prefix=/glade/work/jsimkins/FRE-NCtools/bin --with-mpi
make

```

Following the `make` step, I receive this error:

```
make[2]: Entering directory '/glade/work/jsimkins/FRE-NCtools/tools/libfrencutils'
icc -DHAVE_CONFIG_H -I. -I../..    -I/glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/include -I/glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/include -g -O2 -MT affinity.o -MD -MP -MF .deps/affinity.Tpo -c -o affinity.o affinity.c
mv -f .deps/affinity.Tpo .deps/affinity.Po
icc -DHAVE_CONFIG_H -I. -I../..    -I/glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/include -I/glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1/include -g -O2 -MT create_xgrid.o -MD -MP -MF .deps/create_xgrid.Tpo -c -o create_xgrid.o create_xgrid.c
create_xgrid.c(1313): error: expected an expression
          if(fabs(determ) < EPSLN30) {
             ^

compilation aborted for create_xgrid.c (code 2)
Makefile:418: recipe for target 'create_xgrid.o' failed
```

Even after trying several adaptations of the recipe above, I still receive this error. After reviewing some of the other issues on this repo, I think it would be useful to include an `env.sh` for Cheyenne.

**Comment by underwoo** [comment]
Unfortunately, many of us do not have accounts on cheyenne, and cannot generate the env.sh for that system.  We will be happy to include an env.sh if you have one.  

However, from the error message you submitted, the problem is that the version of GCC that is found first in your PATH is too old.  I realize you are using the Intel compiler, but Intel has a dependency on GCC.  Please check with your system admins on how to get a newer version of GCC included in your PATH before the system GCC.  On one of the other NOAA systems, the system admins had to make an adjustment to the Intel module file(s) to make this easier for the user.

**Comment by underwoo** [comment]
@jsimkins2, as mentioned previously, if you do generate a env.sh for the Cheyenne system please submit a PR and we will include it.
